### ISSUE TITLE
ANS gives NaN

### ISSUE THREAD

**Issue by TheRealJoci** [dariomrk/Calculator-React#2]
Scrolling through the history disables the use of ANS, to recreate:
  * with history existant and answer still on screen, press:
    * <
    * \>
    * ANS

To my understanding the > makes the state a NaN so ANS has nothing even though it's sill present on screen.

**Comment by dariomrk** [comment]
Thank you @TheRealJoci for the bug report and help on the fix. Appreciate it.
Fix is merged. Issue closed.

**Comment by dariomrk** [comment]
Fix is merged. Issue closed.
